#!/bin/bash

# colors for printing
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

FLAGS='-lcurl'
DEPENDENCIES='../aoc.c'

for i in *_tests.c
do
    echo -e "- building ${BLUE}$i${NC}"
    if gcc $i $DEPENDENCIES $FLAGS -o "${i%.c}.out"; then
        echo -e "- build ${GREEN}succeeded!${NC}"
        echo "- running file"
        ./"${i%.c}.out"
    else
        echo "$i build ${RED}failed${NC}..."
    fi
done

rm *.out